/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RssReader;

import RssReader.domain.Argument;
import RssReader.domain.Article;
import RssReader.factory.ConvertServiceFactory;
import RssReader.factory.InputServiceFactory;
import RssReader.service.convert.ConvertService;
import RssReader.util.ConvertArgumentUtils;
import com.rometools.rome.io.FeedException;

import java.io.IOException;
import java.util.List;

public class App {

    public static void main(String[] args) throws IOException, FeedException {
        System.out.println("Start RssReader");
        Argument argument = ConvertArgumentUtils.convertArgument(args);

        List<Article> articleList = InputServiceFactory.create(argument).inputArticle(argument.getInput());

        articleList = convert(articleList, argument);

        // TODO出力

        System.out.println("-i:" + argument.getInput());
        System.out.println("-c:" + argument.getConvertTypeList().get(0));
        System.out.println("-o:" + argument.getOutput());
    }

    private static List<Article> convert(List<Article> articleList, Argument argument) {
        List<ConvertService> convertServiceList = ConvertServiceFactory.create(argument);

        for (ConvertService convertService: convertServiceList) {
            articleList = convertService.convert(articleList);
        }

        return articleList;
    }
}
