/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RssReader;

import RssReader.constant.ArgumentTypeEnum;
import RssReader.util.ConvertArgumentUtils;

import java.util.Map;

public class App {

    public static void main(String[] args) {
        System.out.println("Start RssReader");
        Map<ArgumentTypeEnum, String> argMap = ConvertArgumentUtils.convertArgument(args);

        System.out.println("-i:" + argMap.get(ArgumentTypeEnum.INPUT));
        System.out.println("-c:" + argMap.get(ArgumentTypeEnum.CONVERT_TYPE));
        System.out.println("-o:" + argMap.get(ArgumentTypeEnum.OUTPUT));
    }
}
